name: Run CI Web API Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Download Repository
      - uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Browser
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          chrome-version: 'stable'

      # Setup Gradlew
      - name: Setup gradlew
        run: chmod +x ./gradlew

      - name: Clean project
        run: ./gradlew clean

      # Execute the gradle command for running the cucumber test
      - name: Execute api Test
        run: ./gradlew apiTest

      - name: Execute web Test
        run: ./gradlew webTest

      #Results documentation
      - name: Archive API Test Results
        uses: actions/upload-artifact@4.3.0
        if: always()
        with:
          name: api test reports
          path: build/reports/tests/apiTest

      - name: Archive Web Test Results
        uses: actions/upload-artifact@4.3.0
        if: always()
        with:
          name: web test reports
          path: reports/webTest-report.html
